FROM nginx:alpine AS base

FROM node:20.13.1 AS build

ARG VITE_API_BASE_PORTAL
ARG VITE_API_BASE_ADMIN
ARG VITE_BACKEND_BASE
ARG VITE_STORAGE
ARG VITE_BASE_URL_ADMIN
ARG VITE_BASE_URL_PORTAL
ARG VITE_EMAIL_SUPPORT
ARG VITE_BASE_DIR_ADMIN
ARG VITE_BASE_DIR_PORTAL

ENV VITE_API_BASE_PORTAL=$VITE_API_BASE_PORTAL
ENV VITE_API_BASE_ADMIN=$VITE_API_BASE_ADMIN
ENV VITE_BACKEND_BASE=$VITE_BACKEND_BASE
ENV VITE_STORAGE=$VITE_STORAGE
ENV VITE_BASE_URL_ADMIN=$VITE_BASE_URL_ADMIN
ENV VITE_BASE_URL_PORTAL=$VITE_BASE_URL_PORTAL
ENV VITE_EMAIL_SUPPORT=$VITE_EMAIL_SUPPORT
ENV VITE_BASE_DIR_ADMIN=$VITE_BASE_DIR_ADMIN
ENV VITE_BASE_DIR_PORTAL=$VITE_BASE_DIR_PORTAL

WORKDIR /src/admin
COPY ADMIN_PANEL/. .
RUN npm install

WORKDIR /src/portal
COPY LMS_PORTAL/. .
RUN npm install

FROM build AS publish
WORKDIR /src/admin
RUN npm run build

WORKDIR /src/portal
RUN npm run build

FROM base AS final
ARG VITE_BASE_DIR_ADMIN
ARG VITE_BASE_DIR_PORTAL

COPY nginx.conf.template /etc/nginx/nginx.conf.template
RUN envsubst '$VITE_BASE_DIR_ADMIN $VITE_BASE_DIR_PORTAL' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf

COPY --from=publish /src/admin/dist/. /var/www/admin
COPY --from=publish /src/portal/dist/. /var/www/portal
